# Generated by Django 5.0.2 on 2024-02-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titel')),
                ('runtime', models.IntegerField(verbose_name='Laufzeit')),
                ('language', models.CharField(max_length=50, verbose_name='Sprache')),
                ('fsk', models.IntegerField(default=16, verbose_name='Fsk')),
                ('year', models.IntegerField(default=1980, verbose_name='Jahr')),
                ('dolby', models.BooleanField(default=True, verbose_name='Dolby 5.1 (j/n)')),
                ('description', models.TextField(verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filme',
            },
        ),
    ]
